version: '2.1'
services:

  # To run this image, you must create a .env file with following content:
  # BACKEND_URL=...   # backend API base url (the part before "/api/...")
  # BOT_TOKEN=...     # bot token

  grafolean-ping-bot:
    # If you wish to load an explicit version, change the next line. For example:
    #   image: grafolean/grafolean-ping-bot:v1.0.0
    image: grafolean/grafolean-ping-bot
    container_name: grafolean-ping-bot
    environment:
      # Backend url must be set to the address of the Grafolean backend, for example this uses Grafolean hosted service:
      # - BACKEND_URL=https://grafolean.com/api
      # IMPORTANT: '127.0.0.1' and 'localhost' are _never_ correct addresses for Grafolean backend, because they translate
      # to container, not host.
      - BACKEND_URL=${BACKEND_URL}
      # To use PING bot, a bot with the protocol "ping" must be added via user interface, then the token needs to be copied here:
      - BOT_TOKEN=${BOT_TOKEN}
      # Interval between fetching information about jobs:
      - JOBS_REFRESH_INTERVAL=${JOBS_REFRESH_INTERVAL:-60}
    restart: always
